Feature buildings
jakub-galazka/invpdb pull request #2
Opened 2022-11-04 16:22 UTC by MarceliG

Script to make CSV - table building.

2022-11-04 22:07 UTC, jakub-galazka approved these changes
Most of the changes have been reviewed in an earlier pull request. Better not to duplicate changes this way as this leads to potential conflicts.

2022-11-04 22:07 UTC, jakub-galazka commented on scripts/create_buildings.py
> +            "null"
`"null"` will be imported as a string variable into the database. Use an empty string instead.

2022-11-04 22:11 UTC, jakub-galazka requested changes

2022-11-04 22:11 UTC, jakub-galazka commented on scripts/create_buildings.py
> +            "null"
**CRITICAL BUG!!!**

2022-11-05 17:08 UTC, closed without merging

2022-11-05 17:08 UTC, galik93 approved these changes